

class CrocodileConstants:

    AXIS_X_TO_CHANGE_CROCODILE = 350
    CROCODILE_ONE = 635
    CROCODILE_TWO = 630
    CROCODILE_THREE = 625
    QUANTITY_OF_CROCODILE = 3
    VELOCITY_TO_CHANGE_IMAGE = 1
    VELOCITY = 6